services:
  - type: web
    name: viralis-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
